<?php

return [
    'movies' => [
        [
            'title' => 'The Godfather',
            'description' => 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
            'producer' => 'Francis Ford Coppola',
            'release_date' => '1972-03-24',
            'rt_score' => 4,
            'image' => 'movies/movie1.jpg',
        ],
        [
            'title' => 'Pulp Fiction',
            'description' => 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
            'producer' => 'Quentin Tarantino',
            'release_date' => '1994-10-14',
            'rt_score' => 5,
            'image' => 'movies/movie2.jpg',
        ],
        [
            'title' => 'Inception',
            'description' => 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
            'producer' => 'Christopher Nolan',
            'release_date' => '2010-07-16',
            'rt_score' => 4,
            'image' => 'movies/movie1.jpg',
        ],
        [
            'title' => 'The Dark Knight',
            'description' => 'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.',
            'producer' => 'Christopher Nolan',
            'release_date' => '2008-07-18',
            'rt_score' => 5,
            'image' => 'movies/movie2.jpg',
        ],
        [
            'title' => 'Fight Club',
            'description' => 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much more.',
            'producer' => 'David Fincher',
            'release_date' => '1999-10-15',
            'rt_score' => 5,
            'image' => 'movies/movie1.jpg',
        ],
        [
            'title' => 'Forrest Gump',
            'description' => 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
            'producer' => 'Robert Zemeckis',
            'release_date' => '1994-07-06',
            'rt_score' => 4,
            'image' => 'movies/movie2.jpg',
        ],
        [
            'title' => 'The Matrix',
            'description' => 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
            'producer' => 'Lana Wachowski, Lilly Wachowski',
            'release_date' => '1999-03-31',
            'rt_score' => 5,
            'image' => 'movies/movie1.jpg',
        ],
        [
            'title' => 'The Shawshank Redemption',
            'description' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
            'producer' => 'Frank Darabont',
            'release_date' => '1994-09-23',
            'rt_score' => 5,
            'image' => 'movies/movie2.jpg',
        ],
        [
            'title' => 'Gladiator',
            'description' => 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
            'producer' => 'Ridley Scott',
            'release_date' => '2000-05-05',
            'rt_score' => 4,
            'image' => 'movies/movie1.jpg',
        ],
        [
            'title' => 'Interstellar',
            'description' => 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
            'producer' => 'Christopher Nolan',
            'release_date' => '2014-11-07',
            'rt_score' => 5,
            'image' => 'movies/movie2.jpg',
        ],
        [
            'title' => 'The Silence of the Lambs',
            'description' => 'A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer.',
            'producer' => 'Jonathan Demme',
            'release_date' => '1991-02-14',
            'rt_score' => 5,
            'image' => 'movies/movie1.jpg',
        ],
        [
            'title' => 'Saving Private Ryan',
            'description' => 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
            'producer' => 'Steven Spielberg',
            'release_date' => '1998-07-24',
            'rt_score' => 5,
            'image' => 'movies/movie2.jpg',
        ],
        [
            'title' => 'Schindler\'s List',
            'description' => 'In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
            'producer' => 'Steven Spielberg',
            'release_date' => '1993-12-15',
            'rt_score' => 5,
            'image' => 'movies/movie1.jpg',
        ],
        [
            'title' => 'Se7en',
            'description' => 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
            'producer' => 'David Fincher',
            'release_date' => '1995-09-22',
            'rt_score' => 5,
            'image' => 'movies/movie2.jpg',
        ],
        [
            'title' => 'Braveheart',
            'description' => 'Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.',
            'producer' => 'Mel Gibson',
            'release_date' => '1995-05-24',
            'rt_score' => 4,
            'image' => 'movies/movie1.jpg',
        ],
    ],
];
